kafka.topic:
   user-random-topic: user-random-topic
   user-created-topic: user-created-topic

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:9000/learnKafka?options=-c%20TimeZone=UTC
    username: testUser
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: update
        show-sql: true
        properties:
            hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
            jdbc.time_zone: UTC
  kafka:
    bootstrap-servers: localhost:9092
    producer:
        key-serializer: org.apache.kafka.common.serialization.LongSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        properties:
            spring.json.add.type.headers: false
