server:
  port: 8081

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:9000/learnKafka?options=-c%20TimeZone=UTC
    username: testUser
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}